url: ""
baseurl: "https://nurse-link.github.io"

# Site settings
title: Nurse-Link
email: your-email@domain.com
description: "Nurse-Link"


# Team names, titles and social links
people:
- name: Jieun Seong
  pic: 1
  position: Integrated Ph.D. Student
  social:
    - title: twitter
      url: "https://x.com/jieunseong_"
    - title: email
      url: mailto:jieun3891@snu.ac.kr
    - title: linkedin
      url: "https://www.linkedin.com/in/jieunseong"

- name: Jisu Son
  pic: 2
  position: M.S Student
  social:
    - title: twitter
      url: "https://x.com/wisdomsu_"
    - title: email
      url: mailto:blanksoo15@gmail.com
    - title: linkedin
      url: "https://www.linkedin.com/in/jisu-son-3b7567351"


# Build settings
markdown: kramdown
permalink: pretty
kramdown : 
  input: GFM
  hard_wrap: false
  parse_block_html: true
  
